version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - misspell
    - unconvert
    - gocritic

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/ethpandaops/mcp
